name: sartor_order_management
description: A Flutter application for managing clothing measurements and orders.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  supabase_flutter: ^2.5.4
  postgrest: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # UI and Visualization
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  video_player: ^2.10.0
  hive_flutter: ^1.1.0
  
  # Utils
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  share_plus: 12.0.1
  timeago: ^3.6.1
  intl: ^0.20.2
  collection: ^1.18.0
  image_picker: ^1.2.0
  csv: ^5.1.1
  file_picker: ^10.3.3
  mime: ^1.0.5
  
  # PDF Generation
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_dotenv: ^5.1.0
  riverpod_annotation: ^2.3.5
  timeline_tile: ^2.0.0
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.0
  flutter_lints: ^4.0.0
  http: ^1.2.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    - assets/.env.dev
    - assets/.env.prod
    - assets/images/
